### ISSUE TITLE
Windows is deleting zircolite.exe

### ISSUE THREAD

**Issue by jstnk9** [wagga40/Zircolite-Rules#3]
I'm trying to download the binary to run in my lab. I don't understand the reason, but very stupidly every time I unzip the ZIP my Windows automatically deletes the zircolite .EXE (I have disabled Defender, added exclusions, removed updates, and many other things... the binary is still removed)

Has it happened to you? Have you solved this in any way?

**Comment by wagga40** [comment]
Never happened. I've just tested it. It can happen with AV enabled ([some AV detect it](https://www.virustotal.com/gui/file/9b94c58633131d43d8eeb13fd15462c4c97f5166b55112283fdde26c92e9bd8b/detection)) but you seem to have disabled it. A simple workaround is to use the Python version directly from the repo.

By the way, this repo is for Zircolite rulesets, it is better to post your issue [here](https://github.com/wagga40/Zircolite).
