### ISSUE TITLE
Bad commit or intended rules files removed with commit  9326b3f6de1be404d250892feaf1b0c5d5a44a98

### ISSUE THREAD

**Issue by wmetcalf** [wagga40/Zircolite-Rules#4]
A bunch of the rules files were nuked in commit 9326b3f6de1be404d250892feaf1b0c5d5a44a98 was this intentional?

https://github.com/wagga40/Zircolite-Rules/commit/9326b3f6de1be404d250892feaf1b0c5d5a44a98

**Comment by wagga40** [comment]
Hi, thanks for the issue.

the repository is fully automated with github actions, so it was not intentional.

The deleted files are generated with the legacy sigmatools, you can use the files with « pysigma » in the file name.

I will try to find the source of the error as soon as I can.

**Comment by wagga40** [comment]
I've edited the actions, but it is a temporary workaround. Basically, I have replaced the "full" rulesets generated with legacy sigmatools by the ones generated with pysigma.

I think I will remove the rulesets generated with legacy sigmatools pretty soon to avoid these kind of problems.

**Comment by wmetcalf** [comment]
Okay sounds good
